### ISSUE TITLE
Try-catch in Bynder.Api.OAuthClient.Post(String uri, String postData)

### ISSUE THREAD

**Issue by maansson** [XSARUS/inriver-bynder#8]
We have seen that System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode() called by Bynder.Api.OAuthClient.Post is throwing errors sometimes. This is causing a Connect error in inRiver instead of just a Log.Error. This means that the EntityListener is pilling up with Errors in the Processing area of the Extensions. 

I don't know if this is by design?

https://github.com/XSARUS/inriver-bynder/blob/1588e5d0d9176e808109702ac746963b48308b38/BynderExtension/Api/OAuthClient.cs#L83

**Comment by c-vandam** [comment]
First of all, sorry for the late response. 

Try catch is done in the calling methods: 
- the events 
- the execute method of the scheduled extension. 

In the catch we log the exception, so we handle this in the extension and won't let inRiver handle it. The extension must stop processing when a part of the extension fails, so we keep this by design.

I removed the redundant ToString calls on the strings you pointed out.
